# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Doxee CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'corretto'
        cache: maven
    - name: Build & Test
      uses: ./.github/actions/build
  deployment-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: deploy 
        run: echo "Deploy on $NAME"
      - shell: bash
        run: |
          1.0.0 > version.txt        
      - name: Share VERSION variable
        uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
      - name: Download version from build step
        uses: actions/download-artifact@v5
        with:
          name: version
      - shell: bash
        run: |
          value=`cat version.txt`
          echo "version $value"
  deployment-prod:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy 
        run: echo "Deploy on [${{ vars.NAME }}]"        


